services:
  api:
    image: jiebaef/primeleague-helper
    environment:
      DATABASE_URL: ${DATABASE_URL}
    build:
      context: ./primeleague-helper
      dockerfile: Dockerfile
    ports:
      - "42069:42069"
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:15.2-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_HOST_PORT}:${PG_GUEST_PORT}"
    volumes:
      - ~/.docker_data/primeleague-helper/data/postgres:/var/lib/postgresql/data
