networks:
  postgres_network:
    external: true

services:
  api:
    image: jiebaef/primeleague-helper
    environment:
      DATABASE_URL: "postgres://user1:temppwd@postgres_db:5432/db"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "42069:42069"
    networks:
      - postgres_network
