services:
  api:
    image: jiebaef/primeleague-helper
    # environment:
    #   DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432"
    build:
      context: ./primeleague-helper
      dockerfile: Dockerfile
    ports:
      - "42069:42069"
    # depends_on:
    #   - db
#   db:
#     image: postgres:15.2-alpine
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#     ports:
#       - "5432:5432"
#     volumes:
#       - db:/var/lib/postgresql/data
#
# volumes:
#   db:
#     driver: local
